name: Publish library

on:
  push:
    tags:
      - v*

concurrency: ${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the code 🗄
        uses: actions/checkout@v3

      - name: Setup NodeJs 16 💿
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@nan-projects'

      - name: Setup node modules cache 📦
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
            ~/.cache/Cypress
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Install packages 🏭
        run: yarn install

      - name: Lint the code 🕵
        run: yarn lint

      - name: Check the prettiness of the code 💅
        run: yarn prettier

      - name: Run unit tests 🧪
        run: yarn test

      - name: Build code 🛠
        run: yarn build --baseHref=/tw-react-components/

      - name: Publish the library 🚀
        run: |
          cp LICENCE README.md dist/libs/tw-react-components
          cd dist/libs/tw-react-components
          npm publish --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
